backend:
  name: github
  repo: GhostRicity/esports-cms
  use_graphql: true

media_folder: static/img
public_folder: /img

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: 'string' }
      - { name: description, label: Description, widget: string }
      - { name: 'featuredImage', label: 'Featured Image', widget: 'image', required: true,  tagname: '' }
      - { name: body, label: Body, widget: markdown }

  - label: Research
    name: research
    identifier_field: research
    folder: content/research
    create: true
    fields:
      - { name: path, label: path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: string }
      - { name: 'featuredImage', label: 'Featured Image', widget: 'image', required: true,  tagname: '' }
      - { name: body, label: Body, widget: markdown }

  - label: Tournaments
    name: tournaments
    identifier_field: tournaments
    folder: content/tournaments
    create: true
    fields:
     - { name: path, label: path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title, required: true}
     - { name: description, label: Description, widget: string }
     - { name: 'featuredImage', label: 'Featured Image', widget: 'image', required: true,  tagname: '' }
     - { name: body, label: Body, widget: markdown }
