backend:
  name: github
  repo: GhostRicity/esports-cms
  use_graphql: true

media_folder: content/assets
public_folder: content/assets

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Featured Image", name: "thumbnail", widget: "image"}
      - { name: body, label: Body, widget: markdown }
  - labe: Research
    name: research
    identifier_field: research
    folder: content/research
    create: true
    fields:
      - { name: path, label: mxd }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
